
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "install", type: "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y rpcbind gdb
  SHELL
  config.vm.provision "rpc", run: "always", type: "shell", inline: "sudo rpcbind || true"

  config.vm.network "private_network", type: "dhcp"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.vm.provision :hostmanager, run: "always"

  config.vm.define "coord" do |coord|
    coord.vm.provision "install", type: "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y libc-dev-bin gdb build-essential
    SHELL
    coord.vm.hostname = "coord"
    coord.vm.network "private_network", ip: "192.168.30.2"
  end

  (1..2).each do |i|
    config.vm.define "replica#{i}" do |replica|
      replica.vm.hostname = "replica#{i}"
      replica.vm.network "private_network", ip: "192.168.30.#{i+2}"
    end
  end
end
